language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install tox
# command to run tests
script:
  - tox
# commants to deploy
deploy:
  provider: script
  script: bash <(curl -s https://codecov.io/bash)
  on:
    branch: master
