version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements_ci.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_ci.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements_ci.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 -m pytest --cov=./time_evolving_mpo
            python3 -m coverage xml
      - store_artifacts:
          path: test-reports/
          destination: time_evolving_mpo
      - run:
          name: Upload coverage report
          command: bash <(curl -s https://codecov.io/bash)
